#!/usr/bin/env python3
"""
Record an 8-channel ground-truth clip for DOA validation.

Recording setup (CRITICAL for usable DOA fits):

  * Mic array MIC-UP (capsules facing the open hemisphere). With the
    PCB facing up the chassis shadows the direct path and SRP-PHAT
    locks to floor/wall reflections instead of the source.
  * Robot in the CENTRE of the room, >= 1 m from any wall. Reflections
    that arrive much later than direct path don't dominate the
    cross-correlation lag.
  * Source = stationary speaker on a tripod at MIC-ARRAY HEIGHT,
    ~0.5 m from the ring. At 0.5 m direct path is 16-20 dB louder than
    a single floor bounce, which is what the dominant-source DOA needs
    to lock cleanly.
  * Use the band-limited noise wav generated by
    ``tools/gen_doa_test_signal.py`` (or any broadband stationary
    source -- speech has too much spectral / temporal variability for
    a clean SRP-PHAT peak).

Workflow:

  1. Mount the array mic-up. Mark body 0° (vehicle forward). Place the
     source at the labelled body-frame azimuth.
  2. Run this tool with that azimuth:

         make doa-record AZ=0 LABEL=noise

     (or call this script directly). The tool prompts you to start,
     records 5-6 s of 8-ch (16 kHz int16) via LiveStream from the
     running ``board_audio_server`` (raw mode), and saves four
     artefacts into ``tests/data/doa_dataset/``:

       body_p000deg_noise.wav        # raw 8-channel
       body_p000deg_noise.bf.wav     # AEC + MVDR mono, beam locked to
                                     # the estimated DOA (= what the
                                     # production pipeline produces
                                     # after wake)
       body_p000deg_noise.ch0.wav    # raw single-mic baseline (A/B
                                     # against .bf)
       body_p000deg_noise.json       # metadata + DOA estimates +
                                     # per-clip errors

  3. Repeat for the 4 cardinal angles (0, +90, +180, -90). The combo
     target ``make doa-record-cardinal`` walks you through them.
  4. Run ``make doa-calibrate`` to refit perm + yaw offset against the
     fresh dataset, or ``make doa-test`` for a regression run with the
     current calibration baked into pipeline.py.

The tool auto-plays the test wav via ``aplay`` for the duration of
the capture. The playback speaker's azimuth, not your voice, is what
the mics see, so place the speaker at the labelled body-az.
"""
from __future__ import annotations

import argparse
import json
import subprocess
import sys
import threading
import time
import wave
from pathlib import Path

import numpy as np

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))
sys.path.insert(0, str(
    REPO_ROOT / "thirdparty" / "M2_SDK" / "live_stream" / "host"))

from live_stream import LiveStream, SAMPLE_RATE   # noqa: E402

from audio_frontend.dsp.offline import (   # noqa: E402
    analyze_clip, write_mono_wav,
)


def _spawn_aplay(wav_path: Path, delay_s: float,
                 stop_flag: threading.Event) -> threading.Thread:
    def _run():
        if stop_flag.wait(timeout=delay_s):
            return
        proc = subprocess.Popen(
            ["aplay", "-q", str(wav_path)],
            stdin=subprocess.DEVNULL,
        )
        while proc.poll() is None and not stop_flag.is_set():
            time.sleep(0.05)
        if proc.poll() is None:
            proc.terminate()
            try:
                proc.wait(timeout=2.0)
            except subprocess.TimeoutExpired:
                proc.kill()
    t = threading.Thread(target=_run, daemon=True)
    t.start()
    return t


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--body-az", type=float, required=True,
                    help="ground-truth azimuth in BODY frame, degrees, "
                         "CCW positive (0 = vehicle forward).")
    ap.add_argument("--duration", type=float, default=6.0,
                    help="capture duration in seconds (default 6).")
    ap.add_argument("--label", type=str, default="noise",
                    help="short tag appended to the filename.")
    ap.add_argument("--out-dir", type=str,
                    default="tests/data/doa_dataset")
    ap.add_argument("--mic-yaw-offset-deg", type=float, default=30.0,
                    help="yaw of mic-frame 0° relative to body forward, "
                         "CCW positive. Default matches the M260C "
                         "physical install on this robot.")
    ap.add_argument("--play-wav", type=str, default=None,
                    help="play this wav via aplay for the duration of "
                         "the capture (use a stationary speaker placed "
                         "at the labelled body-az).")
    ap.add_argument("--play-delay-ms", type=int, default=300,
                    help="wait this long after recording starts before "
                         "playing, so the head of the capture has "
                         "ambient (no-voice) reference.")
    ap.add_argument("--host", type=str, default="127.0.0.1")
    ap.add_argument("--port", type=int, default=9999)
    ap.add_argument("--no-confirm", action="store_true",
                    help="skip the 'press Enter to start' prompt.")
    ap.add_argument("--no-analyze", action="store_true",
                    help="skip the offline DSP pass that produces .bf.wav "
                         "and .ch0.wav (raw 8-ch is always saved).")
    ap.add_argument("--dominant-top-k-pct", type=float, default=50.0,
                    help="percentage of loudest hops kept when computing "
                         "the dominant-source DOA. 50%% is robust against "
                         "stray noise; lower (e.g. 25%%) helps when the "
                         "playback duty cycle is short.")
    args = ap.parse_args()

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    body_az = float(args.body_az)
    az_str = f"{body_az:+04.0f}".replace("+", "p").replace("-", "n")
    fname = f"body_{az_str}deg_{args.label}.wav"
    out_path = out_dir / fname
    meta_path = out_path.with_suffix(".json")

    # Convert body→mic azimuth using the same convention as
    # FarfieldAudioSource: mic_az = body_az + mic_yaw_offset_deg, then
    # wrap to [-180, +180).
    mic_az = ((body_az + args.mic_yaw_offset_deg) + 180.0) % 360.0 - 180.0

    print(f"[*] target  body  azimuth = {body_az:+.1f}°")
    print(f"[*] target  mic   azimuth = {mic_az:+.1f}° "
          f"(offset {args.mic_yaw_offset_deg:+.1f}°)")
    print(f"[*] duration = {args.duration:.1f}s")
    print(f"[*] output  -> {out_path}")
    if args.play_wav:
        print(f"[*] auto-playback: {args.play_wav} "
              f"(delay {args.play_delay_ms}ms)")
    if not args.no_confirm:
        try:
            input("    Press Enter to begin recording... ")
        except (EOFError, KeyboardInterrupt):
            print("\nABORTED")
            return 130

    stream = LiveStream(host=args.host, port=args.port,
                        ensure_forward=False)
    stream.connect()

    n = int(args.duration * SAMPLE_RATE)
    play_thread = None
    play_stop = threading.Event()
    if args.play_wav:
        play_thread = _spawn_aplay(
            Path(args.play_wav),
            delay_s=args.play_delay_ms / 1000.0,
            stop_flag=play_stop,
        )

    print(f"[*] capturing {n} samples ({n/SAMPLE_RATE:.2f}s)...")
    t0 = time.monotonic()
    try:
        cap = stream.read_frames(n)   # (T, 8) int16
    finally:
        play_stop.set()
        stream.close()
        if play_thread is not None:
            play_thread.join(timeout=2.0)
    print(f"[*] capture took {time.monotonic()-t0:.2f}s, "
          f"shape={cap.shape}, dtype={cap.dtype}")

    if cap.shape[1] != 8:
        print(f"FAIL: expected 8 channels, got {cap.shape[1]}")
        return 1

    # Save 8-ch wav (libsndfile-readable interleaved int16). Python's
    # wave module supports any channel count as long as we set it.
    pcm = np.ascontiguousarray(cap.astype("<i2"))
    with wave.open(str(out_path), "wb") as w:
        w.setnchannels(8)
        w.setsampwidth(2)
        w.setframerate(SAMPLE_RATE)
        w.writeframes(pcm.tobytes())

    metadata = {
        "filename": out_path.name,
        "body_az_deg": body_az,
        "mic_az_deg": mic_az,
        "mic_yaw_offset_deg": args.mic_yaw_offset_deg,
        "duration_s": float(args.duration),
        "sample_rate": SAMPLE_RATE,
        "n_channels": 8,
        "channel_layout": "0..5=mics ring (60° apart, ccw, ch0=mic_frame_0deg), "
                          "6,7=line-level ref",
        "ring_radius_m": 0.035,
        "label": args.label,
        "play_wav": args.play_wav,
    }

    bf_path = out_path.with_suffix(".bf.wav")
    ch0_path = out_path.with_suffix(".ch0.wav")
    if not args.no_analyze:
        print(f"[*] running pipeline "
              f"(AEC per-mic -> dominant-source DOA -> MVDR locked)...")
        result = analyze_clip(
            cap, mic_yaw_offset_deg=args.mic_yaw_offset_deg,
            sample_rate=SAMPLE_RATE,
            dominant_top_k_pct=args.dominant_top_k_pct,
        )
        write_mono_wav(bf_path, result.bf_mono, sample_rate=SAMPLE_RATE)
        write_mono_wav(ch0_path, result.ch0_mono, sample_rate=SAMPLE_RATE)
        s_err = abs(((result.streaming_body_doa_deg - body_az) + 180.0)
                    % 360.0 - 180.0)
        print(f"[*] streaming DOA  : body {result.streaming_body_doa_deg:+.1f}° "
              f"(mic {result.streaming_mic_doa_deg:+.1f}°)  "
              f"err = {s_err:.1f}°")
        if result.dominant_body_doa_deg is not None:
            d_err = abs(((result.dominant_body_doa_deg - body_az) + 180.0)
                        % 360.0 - 180.0)
            print(f"[*] dominant DOA   : body {result.dominant_body_doa_deg:+.1f}° "
                  f"(mic {result.dominant_mic_doa_deg:+.1f}°, "
                  f"top-{result.dominant_top_k_pct:.0f}%, "
                  f"peak {result.dominant_peak:.2f})  err = {d_err:.1f}°")
        else:
            d_err = None
            print(f"[*] dominant DOA   : (insufficient material)")
        print(f"[*] BF beam locked to mic {result.bf_steered_mic_az_deg:+.1f}°")

        rms_ch0 = float(np.sqrt(np.mean(result.ch0_mono ** 2) + 1e-12))
        rms_bf = float(np.sqrt(np.mean(result.bf_mono ** 2) + 1e-12)) \
            if result.bf_mono.size else 0.0
        bf_gain_db = 20.0 * np.log10((rms_bf + 1e-12) / (rms_ch0 + 1e-12))
        print(f"[*] RMS  ch0 {rms_ch0:.4f}  bf {rms_bf:.4f}  "
              f"(bf-ch0 ratio {bf_gain_db:+.1f} dB)")

        metadata.update({
            "streaming_body_doa_deg": result.streaming_body_doa_deg,
            "streaming_mic_doa_deg": result.streaming_mic_doa_deg,
            "streaming_err_deg": s_err,
            "dominant_body_doa_deg": result.dominant_body_doa_deg,
            "dominant_mic_doa_deg": result.dominant_mic_doa_deg,
            "dominant_peak": result.dominant_peak,
            "dominant_top_k_pct": result.dominant_top_k_pct,
            "dominant_err_deg": d_err,
            "bf_steered_mic_az_deg": result.bf_steered_mic_az_deg,
            "bf_filename": bf_path.name,
            "ch0_filename": ch0_path.name,
            "rms_ch0": rms_ch0,
            "rms_bf": rms_bf,
            "bf_minus_ch0_db": float(bf_gain_db),
        })

    with open(meta_path, "w") as f:
        json.dump(metadata, f, indent=2, ensure_ascii=False)
    print(f"[*] wrote {out_path}")
    if not args.no_analyze:
        print(f"[*] wrote {bf_path}   <- beamformed mono")
        print(f"[*] wrote {ch0_path}  <- single-mic baseline")
    print(f"[*] wrote {meta_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
