"""Offline analysis helpers for the DOA + beamforming pipeline.

Used by ``tools/record_doa_truth.py`` and ``tests/test_doa_real.py``
to run the production ``DspPipeline`` over a captured 8-channel clip
and produce three coordinated artefacts:

* ``streaming`` DOA: the per-frame SRP-PHAT estimate at the end of
  the clip (the ``latest_doa_deg`` value).
* ``dominant`` DOA: a single high-confidence azimuth computed over
  the loudest top-K% of the AEC-cleaned mic buffer. This assumes
  the recording is dominated by a single loud source at the
  labelled azimuth and that any stray quieter sounds are below the
  energy percentile threshold. No VAD / KWS gating is needed.
* ``bf_mono``: a beamformed mono float32 signal generated by
  re-running the pipeline a second time with MVDR locked to the
  dominant DOA (or the streaming estimate as a fallback). DNS is
  forced to passthrough so the caller hears raw beamforming gain,
  not whatever DfNet/DTLN apply on top.

We also expose a single-mic baseline (``ch0_mono``) so callers can
A/B raw vs. beamformed without having to extract a channel from
the 8-ch wav themselves.
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Optional

import numpy as np

from .pipeline import DspPipeline, PipelineConfig


@dataclass
class AnalyzeResult:
    streaming_mic_doa_deg: float
    streaming_body_doa_deg: float
    dominant_mic_doa_deg: Optional[float]
    dominant_body_doa_deg: Optional[float]
    dominant_peak: Optional[float]
    dominant_top_k_pct: float
    bf_mono: np.ndarray            # float32 [-1, 1]
    bf_steered_mic_az_deg: float   # the azimuth MVDR was actually locked to
    ch0_mono: np.ndarray           # float32 [-1, 1]


def _wrap180(deg: float) -> float:
    return float((deg + 180.0) % 360.0 - 180.0)


def analyze_clip(
    signal_8ch: np.ndarray,
    mic_yaw_offset_deg: float = 30.0,
    sample_rate: int = 16000,
    n_mics: int = 6,
    n_ref: int = 2,
    aec_per_mic: bool = True,
    dominant_top_k_pct: float = 50.0,
    block: int = 1600,
) -> AnalyzeResult:
    """Run two pipeline passes over an 8-ch capture.

    Pass 1 (dynamic): SRP-PHAT runs every 100 ms, MVDR follows. The
    pipeline's rolling AEC-cleaned mic buffer is configured large
    enough to retain the entire clip so we can run a one-shot
    dominant-source SRP-PHAT after the pass completes.

    Pass 2 (locked): MVDR steered to the dominant-source DOA (or
    the streaming estimate as a fallback). The mono output is the
    beamformed signal you want to compare against the raw mics.

    Both passes use the production AEC-per-mic order. DNS is forced
    to passthrough so the BF wav is purely AEC + MVDR; this is what
    we want for "raw multi-channel vs beamforming" A/B.
    """
    if signal_8ch.ndim != 2 or signal_8ch.shape[1] < n_mics + n_ref:
        raise ValueError(
            f"expected (T, >= {n_mics + n_ref}), got {signal_8ch.shape}")

    duration_ms = int(signal_8ch.shape[0] * 1000 / sample_rate)
    # Make the pipeline keep AEC-cleaned mics for the entire clip so
    # dominant_doa() can pick the loudest top-K% across the whole
    # recording, not just the last 1.5 s.
    long_window_ms = max(duration_ms + 500, 2000)

    cfg1 = PipelineConfig(
        sample_rate=sample_rate, hop_samples=160,
        n_mics=n_mics, n_ref=n_ref,
        aec_per_mic=aec_per_mic,
        use_doa_for_mvdr=True,
        wake_window_ms=long_window_ms,
        dns_use_passthrough=True,
    )
    pl1 = DspPipeline(cfg1)
    hop = pl1.cfg.hop_samples
    n_total = (signal_8ch.shape[0] // hop) * hop
    sig = signal_8ch[:n_total]
    for s in range(0, n_total, block):
        e = min(n_total, s + block)
        chunk = sig[s:e]
        n_full = (chunk.shape[0] // hop) * hop
        if n_full > 0:
            pl1.process_block(chunk[:n_full])

    # Body / mic-frame conversion convention:
    # mic 0 (logical, after channel perm) sits at body +mic_yaw_offset_deg.
    # The mic frame is therefore body frame rotated by -mic_yaw_offset_deg,
    # so a source at body angle B appears at mic angle (B - offset).
    # Equivalently, body = mic + offset.
    stream_mic_az = float(pl1.latest_doa_deg)
    stream_body_az = _wrap180(stream_mic_az + mic_yaw_offset_deg)
    dom = pl1.dominant_doa(top_k_pct=dominant_top_k_pct)
    if dom is not None:
        dom_mic_az, dom_peak = dom
        dom_body_az = _wrap180(dom_mic_az + mic_yaw_offset_deg)
        steer_az = float(dom_mic_az)
    else:
        dom_mic_az = dom_body_az = dom_peak = None
        steer_az = stream_mic_az

    cfg2 = PipelineConfig(
        sample_rate=sample_rate, hop_samples=160,
        n_mics=n_mics, n_ref=n_ref,
        aec_per_mic=aec_per_mic,
        use_doa_for_mvdr=False,
        static_az_deg=steer_az,
        dns_use_passthrough=True,
    )
    pl2 = DspPipeline(cfg2)
    bf_chunks = []
    for s in range(0, n_total, block):
        e = min(n_total, s + block)
        chunk = sig[s:e]
        n_full = (chunk.shape[0] // hop) * hop
        if n_full == 0:
            continue
        out = pl2.process_block(chunk[:n_full])
        if out.size > 0:
            bf_chunks.append(out)
    bf_mono = (np.concatenate(bf_chunks) if bf_chunks
               else np.zeros(0, dtype=np.float32))

    if signal_8ch.dtype == np.int16:
        ch0_mono = signal_8ch[:n_total, 0].astype(np.float32) / 32768.0
    else:
        ch0_mono = signal_8ch[:n_total, 0].astype(np.float32)

    return AnalyzeResult(
        streaming_mic_doa_deg=stream_mic_az,
        streaming_body_doa_deg=stream_body_az,
        dominant_mic_doa_deg=float(dom_mic_az)
            if dom_mic_az is not None else None,
        dominant_body_doa_deg=float(dom_body_az)
            if dom_body_az is not None else None,
        dominant_peak=float(dom_peak) if dom_peak is not None else None,
        dominant_top_k_pct=float(dominant_top_k_pct),
        bf_mono=bf_mono.astype(np.float32, copy=False),
        bf_steered_mic_az_deg=steer_az,
        ch0_mono=ch0_mono,
    )


def write_mono_wav(path, samples: np.ndarray, sample_rate: int = 16000) -> None:
    """Write a float32 [-1, 1] mono buffer as 16-bit PCM."""
    import wave
    pcm = np.clip(samples, -1.0, 1.0)
    pcm = (pcm * 32767.0).astype("<i2")
    with wave.open(str(path), "wb") as w:
        w.setnchannels(1)
        w.setsampwidth(2)
        w.setframerate(sample_rate)
        w.writeframes(pcm.tobytes())
